### ISSUE TITLE
Cube를 각자 생성하기

### ISSUE THREAD

**Issue by GyeongyeonAn** [C-Bang-Atents/TestCollaboration#1]
## 이슈 내용
- Cube를 브렌치 숫자를 이름으로 각자 생성한다.

## 상세내용
- 각자 할당받은 브렌츠 의 번호가 있다.
- 큐브의 이름은 : Cube_번호
- 안에 컴포넌트 스크립트를 넣는다.
- 스크립트 이름은 Cube_번호
- Start()에서 Debug를 "Cube 생성 : 이름" 을 출력한다.

## 체크리스트
- [x] #3
- [x] #4
- [x] #7
- [x] #5
- [x] #6
- [x] #2

**Comment by legoPepsi** [comment]
마지막 멤버까지 다 햇습니다!
